import { AvatarType } from '../types/avatar'

export const avatars: AvatarType[] = [
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
]

export const premiumAvatars: AvatarType[] = [
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png') },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
  { image: require('../assets/images/avatar.png'), price: 11.58 },
]
