export * from './Home/Home'
export * from './Coins/Coins'
export * from './Fun/Fun'
export * from './Pvp/Pvp'
export * from './CreatePvp/CreatePvp'
export * from './NotFound/NotFound'
export * from './Account/Account'
